### ISSUE TITLE
Live TV does not start

### ISSUE THREAD

**Issue by tnache** [mrolix/plugin.video.neterratv#2]
Hi there,

I was using the plugin on my raspberry pi openelec distribution without any issues, until today. 

I get an error by starting the live tv, referring that I should check the log file.

That is listed there:

18:11:17 335.847168 T:1668633664  NOTICE: Start neterratv plugin
18:11:17 336.211792 T:1668633664  NOTICE: Neterra.TV addon: tvlistlive start
18:11:17 336.411499 T:1668633664   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'cookielib.LoadError'>
                                            Error Contents: '/storage/.kodi/userdata/addon_data/plugin.video.neterratv/cookies.lwp' does not look like a Set-Cookie3 (LWP) format file
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.neterratv/addon.py", line 414, in <module>
                                                plugin.run()
                                              File "/storage/.kodi/addons/script.module.xbmcswift/lib/xbmcswift/plugin.py", line 330, in run
                                                self.dispatch(self.path)
                                              File "/storage/.kodi/addons/script.module.xbmcswift/lib/xbmcswift/plugin.py", line 129, in dispatch
                                                return view_func(**items)
                                              File "/storage/.kodi/addons/plugin.video.neterratv/addon.py", line 155, in tvlistlive
                                                menulist=neterratv.showMusicProds(plugin.get_setting('username'), plugin.get_setting('password'))
                                              File "/storage/.kodi/addons/plugin.video.neterratv/resources/lib/neterratv.py", line 759, in showMusicProds
                                                Neterra = neterra(tv_username, tv_password)
                                              File "/storage/.kodi/addons/plugin.video.neterratv/resources/lib/neterratv.py", line 99, in **init**
                                                self.initCookie()
                                              File "/storage/.kodi/addons/plugin.video.neterratv/resources/lib/neterratv.py", line 123, in initCookie
                                                cj.load(cookiepath, False, False)
                                              File "/home/stephan/projects/openelec-6.0/build.OpenELEC-RPi.arm-6.0.3/Python-2.7.3/.install_pkg/usr/lib/python2.7/cookielib.py", line 1763, in load
                                              File "/home/stephan/projects/openelec-6.0/build.OpenELEC-RPi.arm-6.0.3/Python-2.7.3/.install_pkg/usr/lib/python2.7/_LWPCookieJar.py", line 98, in _really_load
                                            LoadError: '/storage/.kodi/userdata/addon_data/plugin.video.neterratv/cookies.lwp' does not look like a Set-Cookie3 (LWP) format file
                                            -->End of Python script error report<--

Could you advise what went wrong?

Thanks in advance and Best regards,
Tsvetan

**Comment by tnache** [comment]
Issue is gone after manually deleting the /storage/.kodi/userdata/addon_data/plugin.video.neterratv/cookies.lwp file
